# Generated by Django 4.2.1 on 2025-05-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='women',
            options={'ordering': ('-title',)},
        ),
        migrations.AddIndex(
            model_name='women',
            index=models.Index(fields=['time_created'], name='idx_women_time_created'),
        ),
        migrations.AddIndex(
            model_name='women',
            index=models.Index(fields=['title'], name='idx_women_title'),
        ),
    ]
