# Generated by Django 4.2.9 on 2025-05-14 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='women',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='store.categories', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='women',
            name='husband',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wife', to='store.husbands', verbose_name='Муж'),
        ),
        migrations.AddField(
            model_name='women',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='store.tagposts', verbose_name='Тэги'),
        ),
        migrations.AddIndex(
            model_name='tagposts',
            index=models.Index(fields=['tag'], name='idx_tag_posts_tag'),
        ),
        migrations.AddIndex(
            model_name='tagposts',
            index=models.Index(fields=['slug'], name='idx_tag_posts_unq_slug'),
        ),
        migrations.AddIndex(
            model_name='categories',
            index=models.Index(fields=['name'], name='idx_categories_unq_tag'),
        ),
        migrations.AddIndex(
            model_name='categories',
            index=models.Index(fields=['slug'], name='idx_categories_unq_slug'),
        ),
        migrations.AddIndex(
            model_name='women',
            index=models.Index(fields=['title'], name='idx_women_title'),
        ),
        migrations.AddIndex(
            model_name='women',
            index=models.Index(fields=['time_created'], name='idx_women_time_created'),
        ),
        migrations.AddIndex(
            model_name='women',
            index=models.Index(fields=['slug'], name='idx_women_unq_slug'),
        ),
    ]
