# Generated by Django 4.2.1 on 2025-05-11 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_categories_slug_women_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.categories'),
        ),
    ]
