# Generated by Django 4.2.1 on 2025-05-11 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_women_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='women',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='store.categories'),
        ),
        migrations.AlterField(
            model_name='women',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='women',
            name='title',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AddIndex(
            model_name='categories',
            index=models.Index(fields=['name'], name='idx_categories_unq_tag'),
        ),
        migrations.AddIndex(
            model_name='categories',
            index=models.Index(fields=['slug'], name='idx_categories_unq_slug'),
        ),
        migrations.AddIndex(
            model_name='women',
            index=models.Index(fields=['slug'], name='idx_women_unq_slug'),
        ),
        migrations.AddIndex(
            model_name='tagposts',
            index=models.Index(fields=['tag'], name='idx_tag_posts_tag'),
        ),
        migrations.AddIndex(
            model_name='tagposts',
            index=models.Index(fields=['slug'], name='idx_tag_posts_unq_slug'),
        ),
        migrations.AddField(
            model_name='women',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='store.tagposts'),
        ),
    ]
