# Generated by Django 4.2.1 on 2025-05-11 13:12

from django.db import migrations, models
import django.db.models.deletion

from store.models import Husbands


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_tagposts_alter_categories_name_alter_women_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Husbands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='women',
            name='husband',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wum', to='store.husbands'),
        ),
    ]
