# Generated by Django 4.2.1 on 2025-05-11 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_husbands_women_husband'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='husband',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wife', to='store.husbands'),
        ),
    ]
