# Generated by Django 4.2.1 on 2025-05-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_women_husband'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='husbands',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='tagposts',
            options={'ordering': ('tag',)},
        ),
        migrations.AlterModelOptions(
            name='women',
            options={'ordering': ('title',)},
        ),
        migrations.AddField(
            model_name='husbands',
            name='m_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
